apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
  labels:
    app: ott
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ott
  template:
    metadata:
      labels:
        app: ott
    spec:
      containers:
      - name: hotstar-container
        image: satya1031/hotstar:latest
        ports:
        - containerPort: 8080
